@file:Suppress("MaxLineLength", "MaximumLineLength")

package com.jozsefmolnar.newskeletonapp.model.api.constant

val WeatherMap: Map<Int, String> = mapOf(
    0 to "Cloud development not observed or not observable",
    1 to "Cloud generally dissolving or becoming less developed",
    2 to "State of sky on the whole unchanged",
    3 to "Clouds generally forming or developing",
    4 to "Visibility reduced by smoke, e.g. veldt or forest fires, industrial smoke or volcanic ashes",
    5 to "Haze",
    6 to "Widespread dust in suspension in the air, not raised by wind at or near the station at the time of observation",
    7 to "Dust or sand raised by wind at or near the station at the time of observation, but not well-developed dust whirl(s) or sand whirl(s), and no duststorm or sandstorm seen; or, in the case of ships, blowing spray at the station",
    8 to "Well-developed dust or sand whirl(s) seen at or near the station during the preceding hour or at the time of observation, but no dust storm or sandstorm",
    9 to "Duststorm or sandstorm within sight at the time of observation, or at the station during the preceding hour",
    10 to "Mist",
    11 to "Patches of shallow fog or ice fog at the station, whether on land or sea not deeper than about 2 metres on land or 10 metres at sea",
    12 to "More or less continuous shallow fog or ice fog at the station, whether on land or sea, not deeper than about 2m/land or 10m/sea",
    13 to "Lightning visible, no thunder heard",
    14 to "Precipitation within sight, not reaching the ground or the surface of the sea",
    15 to "Precipitation within sight, reaching the ground or the surface of the sea, but distant, i.e. > 5 km from the station",
    16 to "Precipitation within sight, reaching the ground or the surface of the sea, near to, but not at the station",
    17 to "Thunderstorm, but no precipitation at the time of observation",
    18 to "Squalls at or within sight of the station during the preceding hour or at the time of observation",
    19 to "Funnel clouds at or within sight of the station during the preceding hour or at the time of observation",
    20 to "Drizzle (not freezing) or snow grains, not falling as showers, during the preceding hour but not at the time of observation",
    21 to "Rain (not freezing), not falling as showers, during the preceding hour but not at the time of observation",
    22 to "Snow, not falling as showers, during the preceding hour but not at the time of observation",
    23 to "Rain and snow or ice pellets, not falling as showers; during the preceding hour but not at the time of observation",
    24 to "Freezing drizzle or freezing rain; during the preceding hour but not at the time of observation",
    25 to "Shower(s) of rain during the preceding hour but not at the time of observation",
    26 to "Shower(s) of snow, or of rain and snow during the preceding hour but not at the time of observation",
    27 to "Shower(s) of hail, or of rain and hail during the preceding hour but not at the time of observation",
    28 to "Fog or ice fog during the preceding hour but not at the time of observation",
    29 to "Thunderstorm (with or without precipitation) during the preceding hour but not at the time of observation",
    30 to "Slight or moderate duststorm or sandstorm - has decreased during the preceding hour",
    31 to "Slight or moderate duststorm or sandstorm - no appreciable change during the preceding hour",
    32 to "Slight or moderate duststorm or sandstorm - has begun or has increased during the preceding hour",
    33 to "Severe duststorm or sandstorm - has decreased during the preceding hour",
    34 to "Severe duststorm or sandstorm - no appreciable change during the preceding hour",
    35 to "Severe duststorm or sandstorm - has begun or has increased during the preceding hour",
    36 to "Slight/moderate drifting snow - generally low (below eye level)",
    37 to "Heavy drifting snow - generally low (below eye level)",
    38 to "Slight/moderate blowing snow - generally high (above eye level)",
    39 to "Heavy blowing snow - generally high (above eye level)",
    40 to "Fog or ice fog at a a distance at the time of observation, but not at station during the preceding hour, the fog or ice fog extending to a level above that of  the observer",
    41 to "Fog or ice fog in patches",
    42 to "Fog/ice fog, sky visible, has become thinner during the preceding hour",
    43 to "Fog/ice fog, sky invisible, has become thinner during the preceding hour",
    44 to "Fog or ice fog, sky visible, no appreciable change during the past hour",
    45 to "Fog or ice fog, sky invisible, no appreciable change during the precedinghour",
    46 to "Fog or ice fog, sky visible, has begun or has become thicker duringpreceding hour",
    47 to "Fog or ice fog, sky invisible, has begun or has become thicker during thepreceding hour",
    48 to "Fog, depositing rime, sky visible",
    49 to "Fog, depositing rime, sky invisible",
    50 to "Drizzle, not freezing, intermittent, slight at time of ob.",
    51 to "Drizzle, not freezing, continuous, slight at time of ob.",
    52 to "Drizzle, not freezing, intermittent, moderate at time of ob.",
    53 to "Drizzle, not freezing, continuous, moderate at time of ob.",
    54 to "Drizzle, not freezing, intermittent, heavy at time of ob.",
    55 to "Drizzle, not freezing, continuous, heavy at time of ob.",
    56 to "Drizzle, freezing, slight",
    57 to "Drizzle, freezing, moderate or heavy (dense)",
    58 to "Rain and drizzle, slight",
    59 to "Rain and drizzle, moderate or heavy",
    60 to "Rain, not freezing, intermittent, slight at time of ob.",
    61 to "Rain, not freezing, continuous, slight at time of ob.",
    62 to "Rain, not freezing, intermittent, moderate at time of ob.",
    63 to "Rain, not freezing, continuous, moderate at time of ob.",
    64 to "Rain, not freezing, intermittent, heavy at time of ob.",
    65 to "Rain, not freezing, continuous, heavy at time of ob.",
    66 to "Rain, freezing, slight",
    67 to "Rain, freezing, moderate or heavy",
    68 to "Rain or drizzle and snow, slight",
    69 to "Rain or drizzle and snow, moderate or heavy",
    70 to "Intermittent fall of snowflakes, slight at time of ob.",
    71 to "Continuous fall of snowflakes, slight at time of ob.",
    72 to "Intermittent fall of snowflakes, moderate at time of ob.",
    73 to "Continuous fall of snowflakes, moderate at time of ob.",
    74 to "Intermittent fall of snowflakes, heavy at time of ob.",
    75 to "Continuous fall of snowflakes, heavy at time of ob.",
    76 to "Diamond dust (with or without fog)",
    77 to "Snow grains (with or without fog)",
    78 to "Isolated star-like snow crystals (with or without fog)",
    79 to "Ice pellets",
    80 to "Rain shower(s), slight",
    81 to "Rain shower(s), moderate or heavy",
    82 to "Rain shower(s), violent",
    83 to "Shower(s) of rain and snow, slight",
    84 to "Shower(s) of rain and snow, moderate or heavy",
    85 to "Snow shower(s), slight",
    86 to "Snow shower(s), moderate or heavy",
    87 to "Shower(s) of snow pellets or small hail, with or without rain or rain and snow mixed - slight",
    88 to "Shower(s) of snow pellets or small hail, with or without rain or rain and snow mixed - moderate or heavy",
    89 to "Shower(s) of hail, with or without rain or rain and snow mixed, not associated with thunder - slight",
    90 to "Shower(s) of hail, with or without rain or rain and snow mixed, not associated with thunder - moderate or heavy",
    91 to "Slight rain at time of observation - Thunderstorm during the preceding hour but not at time of observation",
    92 to "Moderate or heavy rain at time of observation - Thunderstorm during the preceding hour but not at time of observation",
    93 to "Slight snow, or rain and snow mixed or hail at time of observation - Thunderstorm during the preceding hour but not at time of observation",
    94 to "Moderate or heavy snow, or rain and snow mixed or hail at time of observation - Thunderstorm during the preceding hour but not at time of observation",
    95 to "Thunderstorm, slight or moderate, without hail, but with rain and/or snow at time of observation",
    96 to "Thunderstorm, slight or moderate, with hail at time of ob.",
    97 to "Thunderstorm, heavy, without hail, but with rain and/or snow at time of observation",
    98 to "Thunderstorm combined with dust/sandstorm at time of observation",
    99 to "Thunderstorm, heavy with hail at time of observation",
)
